### PR TITLE
Added support for new devices

### PR DESCRIPTION
**Pull request by HuffYk**
update to latest pyvesync 2.1.12:
- Added Everest Air Support
- Added Vital 200S and Oasis Mist Models

small updates:
- HA device name changed from device_type to device_name
- air quality and PM sensors moved from "diagnostic" to "sensors" section
- filter life moved to "diagnostic" section
- air quality value sensor changed from AQI to PM25 with correct unit of measure
- corrected documentation & issue tracker links

### CODE REVIEW

**Comment by HuffYk** [comment]
@micahqcade please check this PR - its main benefit is added support of EverestAir into pyvesync lib.

**Comment by HumanSkunk** [comment]
Hi. Not sure what the best way to reach out to the current active contributors of this repo. I have noticed updating to the latest version of HA 2024.8.1 there are a number of warnings about depreciated things in this repo. I am unable to raise any issues on the current reposititories as I am unable to do so. If any of you are able to look at this it would be greatly appreciated.  I currently only have a Corre200s so I dont think the second issue has any impact on me. 

One is:

```Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 10:00:14 (10 occurrences)
Last logged: 10:01:30

Detected that custom integration 'vesync' calls async_forward_entry_setup for integration, vesync with title: <redacted>@<redacted>.com and entry_id: 2390b00b1755e41983fa7b5f6c911312, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/vesync/__init__.py, line 93: hass.async_create_task(forward_setup(config_entry, p)), please create a bug report at https://github.com/vlebourl/custom_vesync
````
and

````Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 10:01:28 (5 occurrences)
Last logged: 10:01:30

DEVICE_CLASS_TEMPERATURE was used from vesync, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please report it to the author of the 'vesync' custom integration
TEMP_CELSIUS was used from vesync, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'vesync' custom integration
TIME_MINUTES was used from vesync, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'vesync' custom integration
ENERGY_KILO_WATT_HOUR was used from vesync, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'vesync' custom integration
POWER_WATT was used from vesync, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'vesync' custom integration`

**Comment by micahqcade** [comment]
Thank you I'll look into this asap

**Comment by x10** [comment]
@micahqcade looking for the best place to file an issue/question so sorry for jumping on this PR....

Do know if you support the Levoit humidifiers with this?

**Comment by micahqcade** [comment]
Yes, they are mostly supported as far as I know.

**Comment by x10** [comment]
@micahqcade unfortunately my Levoit 6000S is not supported last I tried. It's an amazing new (large) humidier by Levoit that just has never worked in HA for me.

I also made an official ask on the core here and it is starting to get more traction. https://github.com/home-assistant/core/issues/129120

**Pull request merged**
