### PR TITLE
Fixed deprecation

### PR DESCRIPTION
**Pull request by AndreaTomatis**
Fixed deprecation emerged in latest HA version.

### CODE REVIEW

**Comment by jjrytko** [comment]
Could someone check and approve this? Would be nice to get rid of those warnings that get printed to log every time home assistant starts...

**Comment by jjrytko** [comment]
@micahqcade perhaps?

**Comment by micahqcade** [comment]
Merged. Sorry

**Comment by RobertD502** [comment]
@micahqcade 
Unless @AndreaTomatis is going to be the repo owner/maintainer going forward, the documentation and issue tracker urls should be pointing to this repo and not what is seen in this PR.

**Pull request merged**
